class AppImages {
  static const String imagesPathsbackground = "assets/Backgrounds/";
  static const String splineonborad = imagesPathsbackground + "Spline.png";
  static const String course = "assets/Backgrounds/course3.jpg";
  static const String profile = "assets/Backgrounds/profile.png";
  static const String profileinst = "assets/Backgrounds/p.jpg";
  static const String backpic = "assets/Backgrounds/back.jpg";
  static const String instagram = "assets/Backgrounds/instagram.png";
  static const String facebook = "assets/Backgrounds/facebook.png";
  static const String github = "assets/Backgrounds/github.png";
  static const String twitter = "assets/Backgrounds/twitter.png";
  static const String course1 = "assets/Backgrounds/course1.jpg";
  static const String popularcourse = "assets/Backgrounds/popularcourse.jpg";
  static const String auther = "assets/Backgrounds/auther.jpg";
  static const String splashlogo = "assets/Backgrounds/splashlogo.png";
  static const String appleblack = "assets/Backgrounds/appleblack.png";
  static const String applewhite = "assets/Backgrounds/applewhite.png";
  static const String google = "assets/Backgrounds/google.png";
  static const String applogo = "assets/Backgrounds/logo.jpg";
  static const String errorimg = "assets/Backgrounds/errorimg.jpg";
  static const String navbar = "assets/Backgrounds/navbar.png";
  static const String applogotrans = "assets/Backgrounds/logo_trans.png";
  static const String pic1 = "assets/Backgrounds/pic1.png";
  static const String categories = "assets/Backgrounds/cat1.jpeg";
  static const String edu1 = "assets/Backgrounds/edu1.jpg";
  static const String edu2 = "assets/Backgrounds/edu2.jpg";
  static const String edu3 = "assets/Backgrounds/edu3.png";
  static const String nointernet = "assets/Backgrounds/no_internet.png";
}
